### ISSUE TITLE
TypeError toast[type] is not a function

### ISSUE THREAD

**Issue by LlewopNomis** [bobby-didcoding/did_django_google_api_tutorial#1]
Hi Bobby,

I followed through the course at https://www.youtube.com/watch?v=_vCT42vDfgw&t=2396s after receiving the link from freeCodeCamp, the course was great and I learnt a lot. The profile address autofills nicely but I am having issues getting the profile address to update with the following error in the console:
```
Uncaught TypeError: toastr[type] is not a function      main.js:32 
    at ShowAlert (main.js:32)
    at Object.success (main.js:164)
    at fire (jquery-3.6.0.js:3500)
    at Object.fireWith [as resolveWith] (jquery-3.6.0.js:3630)
    at done (jquery-3.6.0.js:9796)
    at XMLHttpRequest.<anonymous> (jquery-3.6.0.js:10057)
```

There is no error showing in the terminal though. I've searched for similar issues that mentioned the issue could be with the version of jQuery so I tried the uncompressed script but had the same problem. 

Have you got any suggestions?

Cheers,

Simon

**Comment by bobby-didcoding** [comment]
Yes, it will be something to do with the jQuery and/or Toastr version. However, it's strange that the error is happening at all. It works my end.
Perhaps add a newer version of the jQuery & toastr JavaScript.

Alternatively, you can remove the toastr code and render the message to alert('message')

Thanks

Bobby
