### ISSUE TITLE
AttributeError: 'WSGIRequest' object has no attribute 'is_ajax'

### ISSUE THREAD

**Issue by cnr91** [bobby-didcoding/did_django_google_api_tutorial#2]
**whenever I run it I get this error.**

  File "C:\did_django_google_api_tutorial\users\views.py", line 92, in form_valid
    if self.request.is_ajax():
AttributeError: 'WSGIRequest' object has no attribute 'is_ajax'

**Comment by bobby-didcoding** [comment]
Hi there,

This page should help please you 👍

https://stackoverflow.com/questions/70419441/attributeerror-wsgirequest-object-has-no-attribute-is-ajax

Thanks
Bobby

**Comment by cnr91** [comment]
Thank you Bobby,

Typing this instead of this fixed the problem.
**Old:**  if request.is_ajax():
**New:** if request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'

But if you don't activate your google api bill, google api doesn't work. That's why I couldn't finish testing your code. :)

I would like to improve myself by web app, I would appreciate if there is a course you can recommend.
